[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"

[build]
  publish = ".output/public"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm generate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
