[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "npx pnpm i --shamefully-hoist --store=node_modules/.pnpm-store && npx pnpm generate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
